"""Recommendation model."""

from datetime import datetime

from sqlalchemy import String, Float, Boolean, DateTime, ForeignKey, JSON, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class Recommendation(Base, TimestampMixin):
    """A betting recommendation generated by the system."""
    
    __tablename__ = "recommendations"
    
    id: Mapped[int] = mapped_column(primary_key=True)
    
    # References
    fixture_id: Mapped[int] = mapped_column(ForeignKey("fixtures.id"), index=True)
    player_id: Mapped[int | None] = mapped_column(ForeignKey("players.id"), nullable=True)
    player_name: Mapped[str] = mapped_column(String(200))
    
    # Market
    market_type: Mapped[str] = mapped_column(String(50))  # goalscorer, assist
    
    # Pricing
    lambda_intensity: Mapped[float] = mapped_column(Float)
    fair_probability: Mapped[float] = mapped_column(Float)
    fair_odds: Mapped[float] = mapped_column(Float)
    
    # Best market odds
    best_bookmaker: Mapped[str] = mapped_column(String(50))
    best_odds: Mapped[float] = mapped_column(Float)
    
    # Edge
    edge: Mapped[float] = mapped_column(Float, index=True)
    classification: Mapped[str] = mapped_column(String(20))  # VALUE, NO_VALUE, AVOID
    confidence: Mapped[float] = mapped_column(Float)
    
    # Explanation
    explanation: Mapped[dict] = mapped_column(JSON)
    
    # Operator workflow
    status: Mapped[str] = mapped_column(String(20), default="pending")  # pending, approved, rejected, executed
    operator_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Result tracking
    result: Mapped[str | None] = mapped_column(String(20), nullable=True)  # won, lost, void, push
    pnl: Mapped[float | None] = mapped_column(Float, nullable=True)
    
    # Timing
    generated_utc: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    decided_utc: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    settled_utc: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    
    def __repr__(self) -> str:
        return f"<Recommendation {self.player_name} {self.market_type} edge={self.edge:.2%}>"
