/**
 * Maps team names (as stored in the DB) to their API-Football team ID.
 * Logo URL: https://media.api-sports.io/football/teams/{id}.png
 *
 * Coverage: Ligue 1, Premier League, Bundesliga, La Liga, Serie A,
 * Champions League teams present in the DB.
 */
export const TEAM_LOGO_IDS: Record<string, number> = {
  // ── Ligue 1 ────────────────────────────────────────────────────────────────
  'Paris Saint-Germain':   85,
  'PSG':                   85,
  'Marseille':             81,
  'Olympique de Marseille':81,
  'Lyon':                  80,
  'Olympique Lyonnais':    80,
  'Monaco':                91,
  'AS Monaco':             91,
  'Lille':                 79,
  'LOSC Lille':            79,
  'Nice':                  84,
  'OGC Nice':              84,
  'Rennes':                111,
  'Stade Rennais':         111,
  'Lens':                  116,
  'RC Lens':               116,
  'Nantes':                83,
  'FC Nantes':             83,
  'Strasbourg':            95,
  'RC Strasbourg':         95,
  'Reims':                 82,
  'Stade de Reims':        82,
  'Toulouse':              96,
  'Toulouse FC':           96,
  'Brest':                 130,
  'Stade Brestois':        130,
  'Stade Brestois 29':     130,
  'Saint-Étienne':         94,
  'AS Saint-Étienne':      94,
  'Saint-Etienne':         94,
  'Metz':                  112,
  'FC Metz':               112,
  'Lorient':               114,
  'FC Lorient':            114,
  'Montpellier':           92,
  'Montpellier HSC':       92,
  'Angers':                76,
  'SCO Angers':            76,
  'Auxerre':               77,
  'AJ Auxerre':            77,
  'Le Havre':              1093,
  'HAC Le Havre':          1093,
  'Paris FC':              570,
  'Clermont':              115,
  'Clermont Foot':         115,

  // ── Premier League ─────────────────────────────────────────────────────────
  'Arsenal':               42,
  'Aston Villa':           66,
  'Brentford':             55,
  'Brighton & Hove Albion':51,
  'Brighton':              51,
  'AFC Bournemouth':       35,
  'Bournemouth':           35,
  'Burnley':               44,
  'Chelsea':               49,
  'Crystal Palace':        52,
  'Everton':               45,
  'Fulham':                36,
  'Ipswich Town':          57,
  'Ipswich':               57,
  'Leeds United':          63,
  'Leeds':                 63,
  'Leicester City':        46,
  'Leicester':             46,
  'Liverpool':             40,
  'Luton Town':            1359,
  'Luton':                 1359,
  'Manchester City':       50,
  'Man City':              50,
  'Manchester United':     33,
  'Man United':            33,
  'Newcastle United':      34,
  'Newcastle':             34,
  'Nottingham Forest':     65,
  'Sheffield United':      62,
  'Sheffield Utd':         62,
  'Southampton':           41,
  'Sunderland':            71,
  'Tottenham Hotspur':     47,
  'Tottenham':             47,
  'West Ham United':       48,
  'West Ham':              48,
  'Wolverhampton Wanderers':39,
  'Wolves':                39,

  // ── Bundesliga ─────────────────────────────────────────────────────────────
  'Bayern München':        157,
  'FC Bayern München':     157,
  'Bayern Munich':         157,
  'Borussia Dortmund':     165,
  'BVB':                   165,
  'RB Leipzig':            173,
  'Bayer Leverkusen':      168,
  'Eintracht Frankfurt':   169,
  'Frankfurt':             169,
  'VfB Stuttgart':         172,
  'Stuttgart':             172,
  'SC Freiburg':           160,
  'Freiburg':              160,
  '1. FC Union Berlin':    182,
  'Union Berlin':          182,
  'VfL Wolfsburg':         161,
  'Wolfsburg':             161,
  'Borussia Mönchengladbach':163,
  "Borussia M'gladbach":   163,
  'Mönchengladbach':       163,
  'SV Werder Bremen':      162,
  'Werder Bremen':         162,
  'Bremen':                162,
  'FC Augsburg':           186,
  'Augsburg':              186,
  '1. FSV Mainz 05':       164,
  'FSV Mainz 05':          164,
  'Mainz 05':              164,
  'Mainz':                 164,
  '1. FC Köln':            167,
  'FC Köln':               167,
  'Köln':                  167,
  'Cologne':               167,
  'TSG Hoffenheim':        172, // Note: approx, will fall back if wrong
  'Hoffenheim':            172,
  '1. FC Heidenheim':      180,
  'FC Heidenheim':         180,
  'Heidenheim':            180,
  'SC Paderborn 07':       192,
  'Paderborn':             192,
  'FC St. Pauli':          183,
  'St. Pauli':             183,
  'Hamburger SV':          174,
  'HSV':                   174,
  'VfL Bochum':            177,
  'Bochum':                177,

  // ── La Liga ────────────────────────────────────────────────────────────────
  'Real Madrid':           541,
  'Barcelona':             529,
  'FC Barcelona':          529,
  'Atletico Madrid':       530,
  'Atlético Madrid':       530,
  'Sevilla':               536,
  'FC Sevilla':            536,
  'Real Betis':            543,
  'Valencia':              532,
  'Villarreal':            533,
  'Real Sociedad':         548,
  'Athletic Club':         531,
  'Athletic Bilbao':       531,
  'Celta Vigo':            538,
  'Deportivo Alaves':      542,
  'Deportivo Alavés':      542,
  'Alavés':                542,
  'Espanyol':              540,
  'RCD Espanyol':          540,
  'Getafe':                546,
  'Osasuna':               727,
  'CA Osasuna':            727,
  'Rayo Vallecano':        728,
  'Girona':                547,
  'Girona FC':             547,
  'Mallorca':              723,
  'RCD Mallorca':          723,
  'Levante UD':            720,
  'Levante':               720,
  'Las Palmas':            746,
  'UD Las Palmas':         746,
  'Cádiz':                 724,
  'Cadiz':                 724,
  'Almería':               717,
  'Almeria':               717,
  'Real Valladolid':       725,
  'Valladolid':            725,
  'Elche':                 742,

  // ── Serie A ────────────────────────────────────────────────────────────────
  'Juventus':              496,
  'Inter':                 505,
  'Internazionale':        505,
  'FC Internazionale':     505,
  'Milan':                 489,
  'AC Milan':              489,
  'Roma':                  497,
  'AS Roma':               497,
  'Napoli':                492,
  'SSC Napoli':            492,
  'Atalanta':              499,
  'Atalanta BC':           499,
  'Lazio':                 487,
  'SS Lazio':              487,
  'Fiorentina':            502,
  'ACF Fiorentina':        502,
  'Torino':                503,
  'FC Torino':             503,
  'Bologna':               500,
  'FC Bologna':            500,
  'Sassuolo':              494,
  'US Sassuolo':           494,
  'Hellas Verona':         504,
  'Verona':                504,
  'Genoa':                 495,
  'CFC Genoa':             495,
  'Udinese':               490,
  'Lecce':                 867,
  'US Lecce':              867,
  'Cagliari':              488,
  'Cagliari Calcio':       488,
  'Monza':                 1640,
  'AC Monza':              1640,
  'Empoli':                511,
  'FC Empoli':             511,
  'Frosinone':             508,
  'Salernitana':           514,
  'Cremonese':             512,
  'US Cremonese':          512,
  'Parma':                 498,
  'Parma Calcio':          498,
  'Venezia':               519,
  'FC Venezia':            519,
  'Como':                  500, // Note: approx for Como Calcio 1907

  // ── Champions League (non-Big-5 clubs) ─────────────────────────────────────
  'Ajax':                  194,
  'AFC Ajax':              194,
  'Benfica':               211,
  'SL Benfica':            211,
  'PSV Eindhoven':         197,
  'PSV':                   197,
  'Club Brugge':           550,
  'Club Brugge KV':        550,
  'Sporting CP':           228,
  'Galatasaray':           213,
  'FC København':          391,
  'FC Copenhagen':         391,
  'Bodø/Glimt':            2259,
  'Bodo/Glimt':            2259,
  'Slavia Prague':         435,
  'SK Slavia Praha':       435,
  'Olympiacos':            660,
  'Olympiakos':            660,
  'Porto':                 212,
  'FC Porto':              212,
  'Qarabag FK':            1120,
  'Qarabag':               1120,
  'Union St.Gilloise':     575,
  'Royale Union SG':       575,

  // ── Noms canoniques français (canonical_teams.name_fr) ─────────────────────
  'Barcelone':             529,
  'Valence':               532,
  'Inter Milan':           505,
  'Naples':                492,
  'Séville':               536,
  'Leverkusen':            168,
  'Francfort':             169,
  'Dortmund':              165,
  'Leipzig':               173,
  'Augsbourg':             186,
  'Mayence':               164,
  'Fribourg':              160,
  'Wolfsbourg':            161,
  'Werder Brême':          162,
  'Wolverhampton':         39,
  'Saint-Pauli':           183,
  'Bruges':                550,
  'Betis':                 543,
  'Celtic':                371,
  'Rangers':               369,
  'Feyenoord':             209,
  'Darmstadt':             185,
  'Kiel':                  178,
  'Dinamo Zagreb':         454,
  'Red Bull Salzbourg':    1062,
  'Shakhtar':              440,
  'Rodez':                 1082,
}

/** Returns the API-Football team ID for a given name, or null if unknown. */
export function getTeamId(name: string): number | null {
  // Direct match
  if (TEAM_LOGO_IDS[name] != null) return TEAM_LOGO_IDS[name]

  // Accent-insensitive / case-insensitive fallback
  const normalized = name.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
  for (const [key, id] of Object.entries(TEAM_LOGO_IDS)) {
    const normKey = key.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
    if (normKey === normalized) return id
  }

  return null
}
